feeds:
  bounties: "https://earn.superteam.fun/api/search/ireland?bountiesLimit=5&grantsLimit=2&userRegion=Ireland%2CGlobal%2CIreland+%28NI+and+ROI%29"
  events: "https://api2.luma.com/ics/get?entity=calendar&id=cal-qfk26kVBexCBTh7"

schedule:
  bounty_check_minutes: 10
  digest_time: "08:00"
  timezone: "Europe/Dublin"

broadcasts:
  group_chat_id: -1002937891185   # your group ID

 
